- name: AL2023 | install java runtime
  dnf:
    name: java-17-amazon-corretto
    state: present

- name: AL2023 | add jenkins repo file
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: AL2023 | import jenkins rpm key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: AL2023 | install jenkins
  dnf:
    name: jenkins
    state: present
