 - name: Debian | update apt cache
   apt:
     update_cache: true
   when: ansible_os_family == 'Debian'

 - name: Install nginx packages
   package:
     name: "{{ nginx_packages }}"
     state: present
