---
- name: AL2023 | install docker engine packages from Amazon Linux repos
  dnf:
    name:
      - docker
      - containerd
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution == 'Amazon'

- name: add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: true
